version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - sistema-ia-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  gerador-mensagens:
    build: ./gerador-mensagens
    container_name: gerador-mensagens
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - sistema-ia-network
    volumes:
      - ./shared-images:/shared-images:ro
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123

  consumidor-face:
    build: ./consumidor-face
    container_name: consumidor-face
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - sistema-ia-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123

  consumidor-team:
    build: ./consumidor-team
    container_name: consumidor-team
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - sistema-ia-network
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123

networks:
  sistema-ia-network:
    driver: bridge

volumes:
  rabbitmq_data: